workflows change, should work now

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -10,8 +10,8 @@ jobs:
     - name: echo the date
       run: echo "The current time and date is $(date)" # Linux command 
 
-    - name: Stimulate a fail
-      run: exit 1
+    #- name: Stimulate a fail
+    #  run: exit 1
 
     - name: echo the current branch
       run: echo ${{ github.ref_name }}
